<!DOCTYPE html>
<html lang="en">

<head>
	<link rel="icon" href="<?= base_url('assets'); ?>/images/Mask Group.png">
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>MINI MBA</title>
	<!-- google-fonts -->
	<link href="//fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
		rel="stylesheet">
	<!-- //google-fonts -->
	<!-- Template CSS Style link -->
	<link rel="stylesheet" href="<?= base_url('assets'); ?>/css/style-starter.css">
	<style>
		body {
			overflow-x: hidden;
		}
		a h4.title-journal{
      color: #000;
	  transition: ease 500ms;
 	 }
		a h4.title-journal:hover{
      color: #9C1718;
 	 }
	</style>
</head>


<body>
	<!--header-->
	<?php $this->load->view('templates/navbar') ?>

	<!--//header-->


	<!-- //inner banner -->

	<!-- call section -->
	<section class="w3l-call-to-action-6" style="margin-top:5%;margin-bottom:5%;">
		<div class="call-sec-style py-5">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-md-4">
						<div class="section-heading text-center mb-sm-5 mb-2">
							<h3 class="title-style mb-2 text-left" style="color:#9B191B; ">Project & Article</h3>
						</div>
					</div>
				</div>
			</div>


			<div class="container d-flex flex-column mb-5">
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample"
												role="button" aria-expanded="false" aria-controls="collapseExample">
												<h4 class="title-journal">Nanti Kita Kelola Sampah
													di Sekolah (NK2SS)
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-5">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Diah R. Sulistiowati</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample">
										<div class="card card-body">
											We inspire to do waste management project at school. Based on the data we
											collected, school produces 1 ton of waste per day. Imagine, if the school
											has the knowledge and capacity to recycle its waste and turn it into
											sell-able item. Each profit can be used as additional funds to support
											school activities. For this project, we will focus on manage the waste
											generated by elementary schools (SD) in Depok city.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/file/d/1WTQs-v5kcekT_MtHc5LdUQ1iAqzn7MBE/view" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/file/d/1WTQs-v5kcekT_MtHc5LdUQ1iAqzn7MBE/view" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample2"
												role="button" aria-expanded="false" aria-controls="collapseExample2">
												<h4 class="title-journal">Program Peningkatan
													Keterampilan Komunikasi Bahasa Inggris Interkultural dan Berpikir
													Kritis sebagai Skil Kunci Abad-21 Bagi Tenaga Pengajar
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-5">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Leviana Vinanda.</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample2">
										<div class="card card-body">
											The project is about delivering teaching training to teachers on
											intercultural programme in English language education. The programme is
											aimed to enrich students' skills beyond mere linguistics or communicative
											skills. With the reality of globalisation and the multicultural world in the
											21th century, integrating intercultural skills in English language education
											is not just necessary but crucial for students to be successful future
											communicators. In order to reach the students, educating teachers is
											considered as the key stage. Hence, the programme utilises teacher education
											for pre or in-service teachers teaching particularly in secondary and
											vocational education.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1mUpvw4df3Cl389hDcMhZO5JrLV5kcPkglEXR_tDwoZA" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1mUpvw4df3Cl389hDcMhZO5JrLV5kcPkglEXR_tDwoZA" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample3"
												role="button" aria-expanded="false" aria-controls="collapseExample3">
												<h4 class="title-journal">Work Life Balance :
													Mental Sehat, Jiwa Kuat, Kerja Akurat
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-6">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Arya Dwari Rahmani</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample3">
										<div class="card card-body">
											Mentorship for Change Project (MCP) focuses on helping near-dropout students
											to regain their spirit and finish their undergraduate studies. In the belief
											that no student should be left behind, we use a design thinking approach in
											the overall stages of the program, including identification of target
											beneficiaries and mentor profiles, activities design, as well as content
											arrangement and its delivery. Through MCP, we strive to bring sustainable
											impact together with our dedicated alumni mentors who will spend time
											listening and finding solutions inspired by their personal journeys.
											Students are expected to be motivated and grow, with extra fun on top.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1Z6Ng6nsUvGR2374OJwEnkTBEypsa4scB" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1Z6Ng6nsUvGR2374OJwEnkTBEypsa4scB" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample4"
												role="button" aria-expanded="false" aria-controls="collapseExample4">
												<h4 class="title-journal">
													Low Quality of soft skills, causing polytechnic graduates difficult
													to get desired job
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-5">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p> Tri Yuli Adriana</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample4">
										<div class="card card-body">
											Low Quality of soft skills, causing polytechnic graduates difficult to get
											desired job
											Based on data from BPS Indonesia in February 2019, the unemployment rate for
											diploma and university graduates tends to increase, 8,5 % for diplomas and
											25 % for university graduates. Paying attention to the voice of customers
											from 2 big Indonesian companies, Pertamina and Astra, it is known that
											candidates fail not because of technical and inteligence aspects but more
											because of soft skills.
											Prof Dr Jumadi on his research told that the biggest contributors to success
											80 % are soft skills and 20 % hard skills. However, in Indonesian education
											system runs reversed, 20 % on soft skills and 80 % hard skills.
											This change project aims to encourage more intensive and quality education
											in making efforts to develop student’s soft skills. By making changes that
											involve students, teachers, infrastructure, curriculum, learning method and
											policies. So that polytechnic graduates will have strength both in hard
											skills and soft skills
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1KycIuLrTTRI2Cno2YLPa_uUgi7Sz5sd4" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1KycIuLrTTRI2Cno2YLPa_uUgi7Sz5sd4" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample5"
												role="button" aria-expanded="false" aria-controls="collapseExample5">
												<h4 class="title-journal">
													Program Kesehatan Mental Untuk Anak-Anak Yatim
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-5">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Maya Sita Darlina</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample5">
										<div class="card card-body">
											Program Kesehatan Mental Untuk Anak-Anak Yatim adalah pemberian pelatihan
											kepada anak-anak yatim untuk memiliki ketrampilan melakukan mekanisme koping
											permasalahan psikologis mereka serta mampu menjadi postif grup supoort buat
											rekan-rekannya yang lain. Selain itu dari project ini salah satu output yang
											akan ditargetkan adalah tersusunnya buku saku panduang kesehatan mental
											untuk anak-anak yatim.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1qL8sZKXNvrvR97fc3iv4zr_4IZnaP5eT" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1qL8sZKXNvrvR97fc3iv4zr_4IZnaP5eT" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample6"
												role="button" aria-expanded="false" aria-controls="collapseExample6">
												<h4 class="title-journal">
													Peran Orangtua dalam Pendidikan Anak &nbsp; &nbsp; &nbsp; &nbsp;
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-5">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Yulia Indriati</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample6">
										<div class="card card-body">
											The covid-19 pandemic has turned homes into classrooms spontaneously.
											Parents play a critical role in facilitating children’s learning process
											during school from home, yet have also struggled in adapting digital
											technology. This project aim to increase parents ability in adapting digital
											technology in order to avoid further learning losses.

											We are adopting design thinking as the framework for this project. We will
											create parents support group led by parents’ volunteer whom play the role as
											mentors. Modules, trainings and post trainings assistance will run as well
											as monitoring, evaluation and learning tools during one year project.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="<?= base_url('assets'); ?>/pdf/sample.pdf" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="<?= base_url('assets'); ?>/pdf/sample.pdf" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample7"
												role="button" aria-expanded="false" aria-controls="collapseExample7">
												<h4 class="title-journal">
													Mentorship for Change
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-5">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Anggita Leviastuti</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample7">
										<div class="card card-body">
											Mentorship for Change Project (MCP) focuses on helping near-dropout students
											to regain their spirit and finish their undergraduate studies. In the belief
											that no student should be left behind, we use a design thinking approach in
											the overall stages of the program, including identification of target
											beneficiaries and mentor profiles, activities design, as well as content
											arrangement and its delivery. Through MCP, we strive to bring sustainable
											impact together with our dedicated alumni mentors who will spend time
											listening and finding solutions inspired by their personal journeys.
											Students are expected to be motivated and grow, with extra fun on top.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1KycIuLrTTRI2Cno2YLPa_uUgi7Sz5sd4" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1KycIuLrTTRI2Cno2YLPa_uUgi7Sz5sd4" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample9"
												role="button" aria-expanded="false" aria-controls="collapseExample9">
												<h4 class="title-journal">
													Safety Net for Non-Governmental Organizations
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-5">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Ranald Indra</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample9">
										<div class="card card-body">
											The covid-19 pandemic has turned homes into classrooms spontaneously.
											Parents play a critical role in facilitating children’s learning process
											during school from home, yet have also struggled in adapting digital
											technology. This project aim to increase parents ability in adapting digital
											technology in order to avoid further learning losses.

											We are adopting design thinking as the framework for this project. We will
											create parents support group led by parents’ volunteer whom play the role as
											mentors. Modules, trainings and post trainings assistance will run as well
											as monitoring, evaluation and learning tools during one year project.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=11KoCAt3ltdRHM9Lb94DjtLUv4R4eQIgU" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=11KoCAt3ltdRHM9Lb94DjtLUv4R4eQIgU" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample8"
												role="button" aria-expanded="false" aria-controls="collapseExample8">
												<h4 class="title-journal">
													Sustainable and Strategic Development Goals of Social Enterprises
													through Government Relations
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-5">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Aga Adi Winawan</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample8">
										<div class="card card-body">
											Pemimpin.id is a social startup aiming to build a leadership ecosystem which
											is inclusive, effective and empowering the underserved and underprivileged
											people in Indonesia as one of the ways to foster human capital Index of the
											country. One of the ways to do this is conducting ASN Academy to strengthen
											leadership and creating real game changers in the public sector. Therefore,
											government relations are required to advocate our business interest to align
											with the government's requirement, and also promote the business solution
											within the government ecosystem to achieve a noble vision of SDM Unggul and
											Indonesia Emas 2045.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1qbFGDyYrKz29d64KKKt9gEiD2fggv3pV" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1qbFGDyYrKz29d64KKKt9gEiD2fggv3pV" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample10"
												role="button" aria-expanded="false" aria-controls="collapseExample10">
												<h4 class="title-journal">
													Pemerataan Kualitas Pendidikan Indonesia: Sebuah Studi Kasus antara
													Sekolah Murid Merdeka (SMM) Jakarta dan Kudus
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-5">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Yason Pranata</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample10">
										<div class="card card-body">
											To further accelerate access and equity of quality education across
											Indonesia, Sekolah Murid Merdeka (SMM) provides quality education through
											blended-learning methods and technology integration. It allows students
											anywhere from Indonesia to have the same access to quality education as
											students from bigger cities, breaking the disparity of education between
											bigger and smaller cities.

											This project will show how the process of learning and also the practice of
											pedagogy is held in one of SMM Hubs in Bulungcangkring Village, Kudus
											Regency. It also aims to investigate the impact on students in SMM Hub
											Kudus, compared with SMM students in Jakarta.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1enJqfiss48AFd9vgVpCNtKNIGjBO6ku4uYJVI5a-b8o" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1enJqfiss48AFd9vgVpCNtKNIGjBO6ku4uYJVI5a-b8o" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample11"
												role="button" aria-expanded="false" aria-controls="collapseExample11">
												<h4 class="title-journal">
													Online Coaching to Empower the Students
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-6">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Rani Indriani Kusumah</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample11">
										<div class="card card-body">
											This change project proposal (Online Coaching to Empower the Students) will
											enable to provide a more targeted, proactive learning experience for ongoing
											teacher growth. With an instructional framework designed to empower
											lecturers, increased teacher professional capacity can be expected for
											lasting impact on students, classrooms, instructional proccess, campuss, and
											communities.

											This change project offers a powerful assets-based coaching framework that
											capitalizes on lecturers’ strengths, internal motivation lecturers and
											students, and professional goals.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1AartIi_QIjx7AuH9GH8B_KA-6DeW-Byo" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1AartIi_QIjx7AuH9GH8B_KA-6DeW-Byo" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample14"
												role="button" aria-expanded="false" aria-controls="collapseExample14">
												<h4 class="title-journal">
													Coaching for Education
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-6">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Rani Indriani Kusumah</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample14">
										<div class="card card-body">
											This change project proposal will enable us to provide a more targeted,
											proactive learning experience for ongoing student growth. With an
											instructional framework designed to empower teachers, increased teacher
											professional capacity can be expected for lasting impact on students,
											classrooms, schools, and communities.

											This project offers a powerful assets-based coaching framework that
											capitalizes on students’ strengths, internal motivation, and goals. The
											Coaching method used in this project is the GROW Model, a simple method for
											goal setting and problem solving.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1UFIwZf_H5RmR4qNLi23YP8iO1Z5zp4Pn" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1UFIwZf_H5RmR4qNLi23YP8iO1Z5zp4Pn" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample12"
												role="button" aria-expanded="false" aria-controls="collapseExample12">
												<h4 class="title-journal">
													MENINGKATKAN MINAT DAN KOMPETENSI BACA TULIS SISWA DENGAN POJOK BACA
													KARYA SISWA DI SEKOLAH
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-8">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>DR NIKMAH NURBAITY S.Pd.,M.Pd.BI.</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample12">
										<div class="card card-body">
											The students’ interest and competence in reading and writing is still low
											compared to other countries. In Pisa 2018 Indonesia was in 74 rank from 78
											countries surveyed by OECD. Pojok Baca Karya Siswa or Students Work Reading
											Corner is aimed to increase students’ interest in reading and to improve
											students’ competence in writing. Students are trained to write their ideas
											in piece of work and the collection of students works are exhibited in
											Reading Corner. Students writing can be printed in paper or books even in
											digital platform. Students will love reading and writing and will be more
											literate.
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1ZLhOj4OOcfBb4IxqIMBo6OHUaHBPjSLYrsQwlrreeak" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1ZLhOj4OOcfBb4IxqIMBo6OHUaHBPjSLYrsQwlrreeak" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-md-9 col-12">
						<div class="container-ibm py-md-4 py-3">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-12">
											<a class=" text-left" data-toggle="collapse" href="#collapseExample13"
												role="button" aria-expanded="false" aria-controls="collapseExample13">
												<h4 class="title-journal">
													AGILE STARTUP FOR THE FUTURE
												</h4>
											</a>
										</div>

										<div class="col-12 col-md-7">
											<div class="d-flex justify-content-around justify-content-md-between">
												<p>Edhu Enriadis Adilingga</p>
												<p>|</p>
												<p>Health Journal</p>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapseExample13">
										<div class="card card-body">
											A huge number of startup establishments in Indonesia is not comparable to
											the developments in the following years. More than 80% of startups don't
											thrive until they go bankrupt before reaching their fifth year. For these
											reasons, we initiated a Social Project: Agile Startup for the Future (ASF)
											aims to prepare and rebuild an agile startup ecosystem to deal with various
											disruptions. It prospects that ASF can facilitate participants in increasing
											their understanding of managing startups, formulating actions to develop
											mentoring skills through mentoring activities until they can produce
											innovations to deal with various business disruptions that might occur in
											Indonesia
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-12 m-auto text-center ">
						<div class="row justify-content-center my-3">
							<div class="col-md-12 mb-2">
								<a href="https://drive.google.com/open?id=1U4HniyBgNeYrAt8Qqo_trCL6IdObUlFN" target="_blank"
									style="text-align: justify;border-color: #9B191B; color: #9B191B;border-radius: 8px;font-size:14px;border:1px solid; padding:10px 18px;">
									<b>View PDF</b> </a>
							</div>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-12">
								<a href="https://drive.google.com/open?id=1U4HniyBgNeYrAt8Qqo_trCL6IdObUlFN" download="sample" class="px-4 py-2"
									style="text-align: justify; background-color: #9B191B; color:white;border-radius: 8px;font-size:14px">Download
									PDF</a>

							</div>
						</div>
					</div>
				</div>
			</div>



		</div>
	</section>
	<!-- //call section -->

	<!-- footer -->
	<?php $this->load->view('templates/footer') ?>

</body>

</html>